[package]
edition = "2021"
name = "nether-gfx"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.5.1"
png = "0.17.9"

[[bench]]
harness = false
name = "bench"
